import './globals.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
    <html lang="en" data-theme='light' >
      <body className=' m-2' >{children}</body>
    </html>
  )
}
